const ExampleJson = {
  tabs: [
    {
      tabId: 1,
      uiControlType: 1,
      row: 1,
      column: 1,
      displaySeqNo: 1,
      parentDisplaySeqNo: 2,
      parentTabID: 0,
      parentAccordionID: 0,
      jquerySelectorID: 'Contract',
      jquerySelectorIDPartial: null,
      displayName: 'Contract',
      layoutClass: 0,
      tableDataEnum: 0,
      isPost: false,
      jsonDataKeyName: null,
    },
  ],
  dynamicFields: [
    {
      uiControlType: 3,
      dynamicFieldId: 0,
      placeholder: null,
      fieldType: 'modal',
      fieldDataType: 'String',
      fieldData: [
        {
          code: 'CONTR',
          description: 'Contracted Wages',
        },
        {
          code: 'WAGES_PT',
          description: 'Wages PT',
        },
        {
          code: 'WAGES_M',
          description: 'Wages M',
        },
      ],
      isReadOnly: false,
      defaultValue: null,
      heading: null,
      headingText: null,
      colorCode: null,
      isRequired: false,
      minLength: 0,
      maxLength: 0,
      isEmail: false,
      postDateFormat: 'dd/MM/yyyy',
      customRegexPattern: '',
      validationMessage: '',
      maxSelectionCount: 0,
      minSelectionCount: 0,
      childFields: [],
      tooltip: null,
      isSingleAPICall: true,
      configurationKey: '',
      apiUrl: '',
      isHeader: false,
      row: 1,
      column: 1,
      displaySeqNo: 6,
      parentDisplaySeqNo: 1,
      parentTabID: 1,
      parentAccordionID: 0,
      jquerySelectorID: 'PayGroup',
      jquerySelectorIDPartial: null,
      displayName: 'Pay Group',
      layoutClass: 6,
      tableDataEnum: 0,
      isPost: false,
      jsonDataKeyName: null,
    },
    {
      uiControlType: 3,
      dynamicFieldId: 0,
      placeholder: null,
      fieldType: 'modal',
      fieldDataType: 'String',
      fieldData: [
        {
          pageNo: '1',
          recordId: 'Page 1',
          date: '2023-04-24',
          reason: '',
        },
        {
          pageNo: '2',
          recordId: 'Page 2',
          date: '2023-09-29',
          reason: '',
        },
      ],
      isReadOnly: false,
      defaultValue: null,
      heading: null,
      headingText: null,
      colorCode: null,
      isRequired: false,
      minLength: 0,
      maxLength: 0,
      isEmail: false,
      postDateFormat: 'dd/MM/yyyy',
      customRegexPattern: '',
      validationMessage: '',
      maxSelectionCount: 0,
      minSelectionCount: 0,
      childFields: [],
      tooltip: null,
      isSingleAPICall: true,
      configurationKey: '',
      apiUrl: '',
      isHeader: false,
      row: 1,
      column: 1,
      displaySeqNo: 3,
      parentDisplaySeqNo: 1,
      parentTabID: 0,
      parentAccordionID: 0,
      jquerySelectorID: 'HistoryRecordSelect',
      jquerySelectorIDPartial: null,
      displayName: null,
      layoutClass: 5,
      tableDataEnum: 0,
      isPost: false,
      jsonDataKeyName: null,
    },
  ],
  pageTableModals: [
    {
      modalID: 'PayGroup-Modal',
      modalTitle: 'Select a PayGroup',
      tablePartialViewName: '_DynamicTable',
      modalTable: null,
      isMultiSelect: false,
      modalDisplayName: null,
      onClickFuncName: '',
      onClickFuncNamePartial: '',
      inputGroupText: null,
      isModalInput: false,
      uiControlType: 3,
      dynamicFieldId: 0,
      placeholder: 'Pay Group',
      fieldType: null,
      fieldDataType: 'String',
      fieldData: {},
      isReadOnly: false,
      defaultValue: null,
      heading: null,
      headingText: null,
      colorCode: null,
      isRequired: false,
      minLength: 0,
      maxLength: 0,
      isEmail: false,
      postDateFormat: 'dd/MM/yyyy',
      customRegexPattern: '',
      validationMessage: '',
      maxSelectionCount: 0,
      minSelectionCount: 0,
      childFields: [],
      tooltip: null,
      isSingleAPICall: true,
      configurationKey: 'PayGroup',
      row: 1,
      column: 1,
      displaySeqNo: 1,
      parentDisplaySeqNo: 1,
      parentTabID: 0,
      parentAccordionID: 0,
      jquerySelectorID: 'PayGroupInput',
      jquerySelectorIDPartial: null,
      displayName: null,
      layoutClass: 0,
      tableDataEnum: 0,
      isPost: true,
      jsonDataKeyName: 'paygroup',
    },
    {
      modalID: 'ReasonGroup-Modal',
      modalTitle: 'Employee Career',
      tablePartialViewName: '_DynamicTable',
      modalTable: null,
      isMultiSelect: false,
      modalDisplayName: null,
      onClickFuncName: 'afterLoadBtnCick',
      onClickFuncNamePartial: '',
      inputGroupText: null,
      isModalInput: false,
      uiControlType: 3,
      dynamicFieldId: 0,
      placeholder: 'Reason Group',
      fieldType: null,
      fieldDataType: 'String',
      fieldData: {},
      isReadOnly: false,
      defaultValue: null,
      heading: null,
      headingText: null,
      colorCode: null,
      isRequired: false,
      minLength: 0,
      maxLength: 0,
      isEmail: false,
      postDateFormat: 'dd/MM/yyyy',
      customRegexPattern: '',
      validationMessage: '',
      maxSelectionCount: 0,
      minSelectionCount: 0,
      childFields: [],
      tooltip: null,
      isSingleAPICall: true,
      configurationKey: 'HistoryRecordSelect',
      row: 1,
      column: 1,
      displaySeqNo: 1,
      parentDisplaySeqNo: 1,
      parentTabID: 0,
      parentAccordionID: 0,
      jquerySelectorID: 'CareerReasonSelect',
      jquerySelectorIDPartial: null,
      displayName: null,
      layoutClass: 0,
      tableDataEnum: 0,
      isPost: true,
      jsonDataKeyName: 'RecordId',
    },
  ],
};
